# Generated by Django 4.2.1 on 2023-05-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("comment_author", models.CharField(max_length=50)),
                ("comment_time", models.DateTimeField()),
            ],
            options={
                "ordering": ["comment_author"],
            },
        ),
    ]
