# Generated by Django 4.2.1 on 2023-05-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_commentmodel_comment_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmodel",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="Make it Hidden?"),
        ),
    ]
