# Generated by Django 4.2.1 on 2023-05-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_commentmodel_comment_connect"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentmodel",
            name="comment_connect",
        ),
        migrations.AddField(
            model_name="commentmodel",
            name="comment_blog",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="main.blogmodel",
            ),
            preserve_default=False,
        ),
    ]
