# Generated by Django 4.2.1 on 2023-05-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_blogmodel_is_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmodel",
            name="blog_image",
            field=models.ImageField(blank=True, null=True, upload_to="blog_images/"),
        ),
    ]
