# Generated by Django 4.2.1 on 2023-05-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_blogmodel_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="blog_image",
            field=models.ImageField(blank=True, null=True, upload_to="image"),
        ),
    ]
